resolver: lts-13.26
packages:
- '.'
extra-deps:
  - git: https://github.com/composewell/streamly
    commit: 92771949adbefd962ad885c43fd1dc65ebc0f2aa
  - bench-show-0.3.0
  - fusion-plugin-types-0.1.0

rebuild-ghc-options: true
