resolver: lts-12.14
packages:
- '.'
extra-deps:
  - gauge-0.2.4
  - streamly-0.6.0

  # for lts-12.0
  - drinkery-0.4
  - bench-show-0.2.2
  - statistics-0.15.0.0
  - dense-linear-algebra-0.1.0.0
  - math-functions-0.3.0.2

  - Chart-1.9
  - Chart-diagrams-1.9
  - SVGFonts-1.6.0.3

rebuild-ghc-options: true
